version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: daily
    # pr will be created for security updates only
    open-pull-requests-limit: 0

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: daily
    ignore:
      - dependency-name: '*'
        update-types:
          ['version-update:semver-patch', 'version-update:semver-minor']